create table if not exists users (ID INTEGER PRIMARY KEY, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, USER_ID INTEGER, USERNAME TEXT, UNIQUE(USER_ID));

create table if not exists groups (ID INTEGER PRIMARY KEY, NAME TEXT NOT NULL, CREATOR INTEGER NOT NULL, activerecord INTEGER DEFAULT 1);

create table if not exists categories (ID INTEGER PRIMARY KEY, CATEGORY TEXT NOT NULL, activerecord INTEGER DEFAULT 1, GROUP_ID INTEGER, UNIQUE(CATEGORY, GROUP_ID), FOREIGN KEY(GROUP_ID) REFERENCES groups(ID));

create table if not exists expenses (ID INTEGER PRIMARY KEY, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, AMOUNT INTEGER, COMMENT TEXT, CATEGORY_ID INTEGER, GROUP_ID INTEGER, USER_ID INTEGER, FOREIGN KEY (CATEGORY_ID)  REFERENCES categories (ID), FOREIGN KEY (GROUP_ID) REFERENCES groups(ID), FOREIGN KEY (USER_ID) REFERENCES users(USER_ID));

create table if not exists user_groups (ID INTEGER PRIMARY KEY, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, USER_ID INTEGER NOT NULL, GROUP_ID INTEGER NOT NULL, UNIQUE(USER_ID, GROUP_ID), FOREIGN KEY (USER_ID) REFERENCES users(ID), FOREIGN KEY (GROUP_ID) REFERENCES groups(ID));
